CREATE DATABASE IF NOT EXISTS SSISREMAKE;
USE SSISREMAKE;

CREATE TABLE IF NOT EXISTS COLLEGES (
	collegecode VARCHAR(10) PRIMARY KEY NOT NULL,
    collegename VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROGRAMS (
	programcode VARCHAR(10) PRIMARY KEY NOT NULL,
    programname VARCHAR(255) NOT NULL,
    collegecode VARCHAR(10) NOT NULL,
    
    FOREIGN KEY (collegecode) REFERENCES COLLEGES(collegecode)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS STUDENTS (
	idnumber VARCHAR(10) PRIMARY KEY NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    yearlevel ENUM('1', '2', '3', '4') NOT NULL,
    gender ENUM('M', 'F') NOT NULL,
    programcode VARCHAR(10),
    
    FOREIGN KEY (programcode) REFERENCES PROGRAMS(programcode)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);