# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCollegeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addCollegeDialog(object):
    def setupUi(self, addCollegeDialog):
        addCollegeDialog.setObjectName("addCollegeDialog")
        addCollegeDialog.resize(448, 369)
        addCollegeDialog.setMinimumSize(QtCore.QSize(448, 369))
        addCollegeDialog.setMaximumSize(QtCore.QSize(448, 369))
        self.collegeCodeLabel = QtWidgets.QLabel(addCollegeDialog)
        self.collegeCodeLabel.setGeometry(QtCore.QRect(20, 130, 124, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.collegeCodeLabel.setFont(font)
        self.collegeCodeLabel.setObjectName("collegeCodeLabel")
        self.collegeNameLabel = QtWidgets.QLabel(addCollegeDialog)
        self.collegeNameLabel.setGeometry(QtCore.QRect(20, 200, 125, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.collegeNameLabel.setFont(font)
        self.collegeNameLabel.setObjectName("collegeNameLabel")
        self.collegeCodeLine = QtWidgets.QLineEdit(addCollegeDialog)
        self.collegeCodeLine.setGeometry(QtCore.QRect(160, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.collegeCodeLine.setFont(font)
        self.collegeCodeLine.setObjectName("collegeCodeLine")
        self.collegeNameLine = QtWidgets.QLineEdit(addCollegeDialog)
        self.collegeNameLine.setGeometry(QtCore.QRect(160, 190, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.collegeNameLine.setFont(font)
        self.collegeNameLine.setObjectName("collegeNameLine")
        self.addCollegeButton = QtWidgets.QPushButton(addCollegeDialog)
        self.addCollegeButton.setGeometry(QtCore.QRect(160, 300, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addCollegeButton.setFont(font)
        self.addCollegeButton.setObjectName("addCollegeButton")
        self.collegeCodeLabel_2 = QtWidgets.QLabel(addCollegeDialog)
        self.collegeCodeLabel_2.setGeometry(QtCore.QRect(140, 30, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.collegeCodeLabel_2.setFont(font)
        self.collegeCodeLabel_2.setObjectName("collegeCodeLabel_2")

        self.retranslateUi(addCollegeDialog)
        QtCore.QMetaObject.connectSlotsByName(addCollegeDialog)

    def retranslateUi(self, addCollegeDialog):
        _translate = QtCore.QCoreApplication.translate
        addCollegeDialog.setWindowTitle(_translate("addCollegeDialog", "Add College"))
        self.collegeCodeLabel.setText(_translate("addCollegeDialog", "COLLEGE CODE:"))
        self.collegeNameLabel.setText(_translate("addCollegeDialog", "COLLEGE NAME:"))
        self.addCollegeButton.setText(_translate("addCollegeDialog", "ADD"))
        self.collegeCodeLabel_2.setText(_translate("addCollegeDialog", "COLLEGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addCollegeDialog = QtWidgets.QDialog()
    ui = Ui_addCollegeDialog()
    ui.setupUi(addCollegeDialog)
    addCollegeDialog.show()
    sys.exit(app.exec_())
