# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addProgramDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addProgramDialog(object):
    def setupUi(self, addProgramDialog):
        addProgramDialog.setObjectName("addProgramDialog")
        addProgramDialog.resize(453, 371)
        self.addprogramlabel = QtWidgets.QLabel(addProgramDialog)
        self.addprogramlabel.setGeometry(QtCore.QRect(140, 20, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.addprogramlabel.setFont(font)
        self.addprogramlabel.setObjectName("addprogramlabel")
        self.programnamelabel = QtWidgets.QLabel(addProgramDialog)
        self.programnamelabel.setGeometry(QtCore.QRect(20, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.programnamelabel.setFont(font)
        self.programnamelabel.setObjectName("programnamelabel")
        self.programNameLine = QtWidgets.QLineEdit(addProgramDialog)
        self.programNameLine.setGeometry(QtCore.QRect(160, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.programNameLine.setFont(font)
        self.programNameLine.setObjectName("programNameLine")
        self.programCodeLine = QtWidgets.QLineEdit(addProgramDialog)
        self.programCodeLine.setGeometry(QtCore.QRect(160, 100, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.programCodeLine.setFont(font)
        self.programCodeLine.setObjectName("programCodeLine")
        self.programcodelabel = QtWidgets.QLabel(addProgramDialog)
        self.programcodelabel.setGeometry(QtCore.QRect(20, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.programcodelabel.setFont(font)
        self.programcodelabel.setObjectName("programcodelabel")
        self.collegecodelabel2 = QtWidgets.QLabel(addProgramDialog)
        self.collegecodelabel2.setGeometry(QtCore.QRect(20, 250, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.collegecodelabel2.setFont(font)
        self.collegecodelabel2.setObjectName("collegecodelabel2")
        self.prcollegecodeBox = QtWidgets.QComboBox(addProgramDialog)
        self.prcollegecodeBox.setGeometry(QtCore.QRect(160, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prcollegecodeBox.setFont(font)
        self.prcollegecodeBox.setObjectName("prcollegecodeBox")
        button_style = """
QPushButton {
    background-color: rgb(114, 137, 218);
    color: white;
    border: none;
    border-radius: 5px;
}
QPushButton:hover {
    background-color: rgb(103, 126, 207);
}
QPushButton:pressed {
    background-color: rgb(92, 115, 196);
}
"""
        self.addProgramButton = QtWidgets.QPushButton(addProgramDialog)
        self.addProgramButton.setGeometry(QtCore.QRect(160, 310, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addProgramButton.setFont(font)
        self.addProgramButton.setObjectName("addProgramButton")
        self.addProgramButton.setStyleSheet(button_style)

        self.retranslateUi(addProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(addProgramDialog)

    def retranslateUi(self, addProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        addProgramDialog.setWindowTitle(_translate("addProgramDialog", "Add Program"))
        self.addprogramlabel.setText(_translate("addProgramDialog", "PROGRAM"))
        self.programnamelabel.setText(_translate("addProgramDialog", "PROGRAM NAME:"))
        self.programcodelabel.setText(_translate("addProgramDialog", "PROGRAM CODE:"))
        self.collegecodelabel2.setText(_translate("addProgramDialog", "COLLEGE CODE:"))
        self.addProgramButton.setText(_translate("addProgramDialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addProgramDialog = QtWidgets.QDialog()
    ui = Ui_addProgramDialog()
    ui.setupUi(addProgramDialog)
    addProgramDialog.show()
    sys.exit(app.exec_())
