# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1822, 1022)
        mainWindow.setMaximumSize(1822, 1022)
        mainWindow.setMinimumSize(1822, 1022)
        mainWindow.setStyleSheet("background-color: rgb(30,33,36); color: rgb(255,255,255);") #changes
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLine.setGeometry(QtCore.QRect(30, 60, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchLine.setFont(font)
        self.searchLine.setObjectName("searchLine")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(410, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(30, 920, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.searchBox = QtWidgets.QComboBox(self.centralwidget)
        self.searchBox.setGeometry(QtCore.QRect(210, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBox.setFont(font)
        self.searchBox.setObjectName("searchBox")
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setGeometry(QtCore.QRect(30, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.sortLabel = QtWidgets.QLabel(self.centralwidget)
        self.sortLabel.setGeometry(QtCore.QRect(1320, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.sortLabel.setFont(font)
        self.sortLabel.setObjectName("sortLabel")
        self.sortBox = QtWidgets.QComboBox(self.centralwidget)
        self.sortBox.setGeometry(QtCore.QRect(1460, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortBox.setFont(font)
        self.sortBox.setObjectName("sortBox")
        self.displayBox = QtWidgets.QComboBox(self.centralwidget)
        self.displayBox.setGeometry(QtCore.QRect(1460, 60, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.displayBox.setFont(font)
        self.displayBox.setObjectName("displayBox")
        self.displayBox.addItem("")
        self.displayBox.addItem("")
        self.displayBox.addItem("")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(1330, 920, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(1490, 920, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(1650, 920, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.sortLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.sortLabel_2.setGeometry(QtCore.QRect(1350, 60, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.sortLabel_2.setFont(font)
        self.sortLabel_2.setObjectName("sortLabel_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGeometry(QtCore.QRect(30, 110, 1771, 801))
        self.tableWidget.setStyleSheet("""
    QTableWidget {
        background-color: rgb(40, 43, 48);
        color: white;
        gridline-color: #5a5a5a;
    }

    QHeaderView::section {
        background-color: rgb(60, 63, 65);
        color: white;
        padding: 4px;
        border: 1px solid #5a5a5a;
    }                                 
    QTableWidget::item:selected {
        background-color: rgb(85, 170, 255);
        color: black;
    }
""")
        button_style = """
QPushButton {
    background-color: rgb(114, 137, 218);
    color: white;
    border: none;
    border-radius: 5px;
}
QPushButton:hover {
    background-color: rgb(103, 126, 207);
}
QPushButton:pressed {
    background-color: rgb(92, 115, 196);
}
"""
        self.searchButton.setStyleSheet(button_style)
        self.refreshButton.setStyleSheet(button_style)
        self.deleteButton.setStyleSheet(button_style)
        self.updateButton.setStyleSheet(button_style)
        self.addButton.setStyleSheet(button_style)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStyleSheet("background-color: rgb(40, 43, 48);") #changes
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1822, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Student Information System"))
        self.searchButton.setText(_translate("mainWindow", "SEARCH"))
        self.refreshButton.setText(_translate("mainWindow", "REFRESH"))
        self.searchLabel.setText(_translate("mainWindow", "SEARCH BY:"))
        self.sortLabel.setText(_translate("mainWindow", "SORT BY:"))
        self.displayBox.setItemText(0, _translate("mainWindow", "STUDENTS"))
        self.displayBox.setItemText(1, _translate("mainWindow", "PROGRAMS"))
        self.displayBox.setItemText(2, _translate("mainWindow", "COLLEGES"))
        self.deleteButton.setText(_translate("mainWindow", "DELETE"))
        self.updateButton.setText(_translate("mainWindow", "UPDATE"))
        self.addButton.setText(_translate("mainWindow", "ADD"))
        self.sortLabel_2.setText(_translate("mainWindow", "SHOW:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
