# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateProgramDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updateProgramDialog(object):
    def setupUi(self, updateProgramDialog):
        updateProgramDialog.setObjectName("updateProgramDialog")
        updateProgramDialog.resize(453, 371)
        self.updateprogramLabel = QtWidgets.QLabel(updateProgramDialog)
        self.updateprogramLabel.setGeometry(QtCore.QRect(100, 20, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.updateprogramLabel.setFont(font)
        self.updateprogramLabel.setObjectName("updateprogramLabel")
        self.updprogramnamelabel = QtWidgets.QLabel(updateProgramDialog)
        self.updprogramnamelabel.setGeometry(QtCore.QRect(20, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updprogramnamelabel.setFont(font)
        self.updprogramnamelabel.setObjectName("updprogramnamelabel")
        self.updprogramNameLine = QtWidgets.QLineEdit(updateProgramDialog)
        self.updprogramNameLine.setGeometry(QtCore.QRect(160, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updprogramNameLine.setFont(font)
        self.updprogramNameLine.setObjectName("updprogramNameLine")
        self.updprogramCodeLine = QtWidgets.QLineEdit(updateProgramDialog)
        self.updprogramCodeLine.setGeometry(QtCore.QRect(160, 100, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updprogramCodeLine.setFont(font)
        self.updprogramCodeLine.setObjectName("updprogramCodeLine")
        self.updprogramcodelabel = QtWidgets.QLabel(updateProgramDialog)
        self.updprogramcodelabel.setGeometry(QtCore.QRect(20, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updprogramcodelabel.setFont(font)
        self.updprogramcodelabel.setObjectName("updprogramcodelabel")
        self.updcollegecodelabel2 = QtWidgets.QLabel(updateProgramDialog)
        self.updcollegecodelabel2.setGeometry(QtCore.QRect(20, 250, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updcollegecodelabel2.setFont(font)
        self.updcollegecodelabel2.setObjectName("updcollegecodelabel2")
        self.updprcollegecodeBox = QtWidgets.QComboBox(updateProgramDialog)
        self.updprcollegecodeBox.setGeometry(QtCore.QRect(160, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updprcollegecodeBox.setFont(font)
        self.updprcollegecodeBox.setObjectName("updprcollegecodeBox")
        self.updateProgramButton = QtWidgets.QPushButton(updateProgramDialog)
        self.updateProgramButton.setGeometry(QtCore.QRect(160, 310, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateProgramButton.setFont(font)
        self.updateProgramButton.setObjectName("updateProgramButton")

        self.retranslateUi(updateProgramDialog)
        QtCore.QMetaObject.connectSlotsByName(updateProgramDialog)

    def retranslateUi(self, updateProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        updateProgramDialog.setWindowTitle(_translate("updateProgramDialog", "Update Program"))
        self.updateprogramLabel.setText(_translate("updateProgramDialog", "EDIT PROGRAM"))
        self.updprogramnamelabel.setText(_translate("updateProgramDialog", "PROGRAM NAME:"))
        self.updprogramcodelabel.setText(_translate("updateProgramDialog", "PROGRAM CODE:"))
        self.updcollegecodelabel2.setText(_translate("updateProgramDialog", "COLLEGE CODE:"))
        self.updateProgramButton.setText(_translate("updateProgramDialog", "UPDATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    updateProgramDialog = QtWidgets.QDialog()
    ui = Ui_updateProgramDialog()
    ui.setupUi(updateProgramDialog)
    updateProgramDialog.show()
    sys.exit(app.exec_())
